{{- range $name, $config := .Values.microservices }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}-sa
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $name }}
automountServiceAccountToken: false
{{- end }}