# Proprietes de l'application
spring:
  application:
    name: clientservice                                   # nom de l'application
  cloud:
    # Activation remontée management dans Eureka
    config:
      service-registry:
        auto-registration:
          register-management: on
  # configuration lien vers serveur Zipkin
  zipkin:
    # SANS DOCKER COMPOSE
    # baseurl: http://localhost:9411/
    # AVEC DOCKER COMPOSE
    baseurl: http://bnkzipkin:9411/
    sender:
      type: web # les requêtes seront envoyés en HTTP
  # Configuration de Sleuth
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    # SANS DOCKER COMPOSE
    # url: jdbc:mysql://localhost:3306/banquebd   # URL mysql
    # SANS DOCKER COMPOSE
    url: jdbc:mysql://bnkmysql:3306/banquebd   # URL mysql
    username: root
    password: root
  jpa:                                                      # Configuration JPA
    database-platform: org.hibernate.dialect.MySQL5Dialect  # On va parler en MySQL
    hibernate:
      # NE PAS LAISSER EN PROD
      ddl-auto: update                                      # strategie create-drop.

# Activation des endpoints pour le monitoring
management:
  endpoints:
    web:
      exposure:
        include:
          env,health,
          info,metrics,
          loggers,mappings, prometheus

# Configuration client de l'annuaire
# Le serveur comptes va s'enregistrer comme un micro-service sur l'annuaire
eureka:
  client:
    serviceUrl:
      # SANS DOCKER COMPOSE
      # defaultZone: http://localhost:10001/eureka/ # url d'accès à l'annuaire
      # AVEC DOCKER COMPOSE
      defaultZone: http://bnkannuaire:10001/eureka/ # url d'accès à l'annuaire

  instance:
    prefer-ip-address: true
    metadata-map:
      prometheus.scrape: "true"
      prometheus.path: "/actuator/prometheus"
      prometheus.port: "${management.server.port}"
      #    instance:
      #      metadataMap:
      # on va surcharger le nom de l'application si plusieurs instances de Client-service ont même IP et même port
      # on surcharge par une valeur random si le nom de l'instance existe déjà.
#        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Configuration du log.
logging:
  level:
    org.springframework.web: INFO # Choix du niveau de log affiché
# Proprietes du serveur d'entreprise
server:
  port: 10011   # HTTP (Tomcat) port