# 1. On crée un secret Kubernetes classique qui contient le token de dev Vault
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: {{ .Values.global.namespace }}
stringData:
  token: "root"
---
# 2. On indique à ESO comment se connecter à Vault en utilisant ce token
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: {{ .Values.global.namespace }}
spec:
  provider:
    vault:
      server: "http://vault.default.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token